version: "3.8"
services:
  borgmatic:
    build: 
        context: .
    volumes:
      # Config location
      - ./data:/data

      # Files to back up
      - ./backupdirs:/backupdirs/

      # Backup location
      - ./backups:/backups/
    environment: 
      - GUID=1000
      - SENDER_EMAIL=SkippyTheSnakeControl@gmail.com
      - SENDER_EMAIL_PASSWORD=FRL2yYRK2m2lTucZ4m^F
      - RECIPIENT=maddogshain132@gmail.com